

CREATE TABLE "users" (
    id        integer                  GENERATED BY DEFAULT AS IDENTITY,
    email     text                     NOT NULL,
    password  text                     NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    role text NOT NULL DEFAULT 'Student',
    CONSTRAINT "PK_Users" PRIMARY KEY ("id")
);